# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'GotEpisodes' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GotEpisodes
  pod 'Swinject', '~> 2.1.0' # Dependency injection
  pod 'ReactiveCocoa', '6.0.0-rc.2' # Functional Reactive Programming
  pod 'Alamofire', '~> 4.4' # Request http
  pod 'ObjectMapper', '~> 2.2' # Mapping json <=> object
  pod 'Timepiece', '~> 1.2' # Gestione evoluta delle date

  target 'GotEpisodesTests' do
    inherit! :search_paths
    # Pods for testing
    
    pod 'Quick'
    pod 'Nimble'
  end

  target 'GotEpisodesUITests' do
    inherit! :search_paths
    # Pods for testing
    
    pod 'Quick'
    pod 'Nimble'
  end

end
